# Generated by Django 6.0 on 2025-12-28 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic_data_generator', '0002_chunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='synthetic_data_generator.chunk')),
            ],
            options={
                'verbose_name': 'Chunk Description',
                'verbose_name_plural': 'Chunk Descriptions',
                'ordering': ['created_at'],
            },
        ),
    ]
