# Generated by Django 6.0 on 2025-12-31 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('synthetic_data_generator', '0003_chunkdescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunkdescription',
            name='chunk',
        ),
        migrations.DeleteModel(
            name='Chunk',
        ),
        migrations.DeleteModel(
            name='ChunkDescription',
        ),
    ]
