# Generated by Django 6.0 on 2025-12-20 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_download', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLToVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(unique=True)),
                ('link_element', models.TextField()),
                ('processed', models.BooleanField(default=False)),
                ('source_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_links', to='html_download.page')),
            ],
        ),
    ]
