# Generated by Django 6.0 on 2025-12-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_download', '0002_urltovisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HREFScraped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('href_url', models.TextField()),
            ],
        ),
    ]
