# Generated by Django 6.0 on 2025-12-23 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_download', '0003_hrefscraped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='page',
            name='filepath',
        ),
    ]
