# Generated by Django 6.0 on 2025-12-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html_download', '0004_remove_page_filename_remove_page_filepath'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='cleaned_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
