# Generated by Django 6.0 on 2025-12-31 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('synthetic_data_generator', '0004_remove_chunkdescription_chunk_delete_chunk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('python_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='synthetic_data_generator.pythonfile')),
            ],
            options={
                'verbose_name': 'Chunk',
                'verbose_name_plural': 'Chunks',
                'ordering': ['updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChunkDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chunk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descriptions', to='chunking.chunk')),
            ],
            options={
                'verbose_name': 'Chunk Description',
                'verbose_name_plural': 'Chunk Descriptions',
                'ordering': ['created_at'],
            },
        ),
    ]
