# Generated by Django 6.0 on 2026-01-18 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunking', '0002_chunkconfig_chunk_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chunk',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
